name: Exercise 2 Plan

on:
  pull_request:
    paths:
      - exercise-2/**
      - .github/workflows/exercise-2.yml
      - .github/workflows/terraform-plan.yml
  push:
    branches:
      - main
    paths:
      - exercise-2/**
      - .github/workflows/exercise-2.yml
      - .github/workflows/terraform-plan.yml
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    uses: ./.github/workflows/terraform-plan.yml
    with:
      working_directory: exercise-2/terraform
    secrets: inherit
